import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import"bootstrap/dist/css/bootstrap.min.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={
            {
              "token": {
                "colorPrimary": "#6a37f4",
                "colorInfo": "#6a37f4"
              }
            }
          }>
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
