import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import"bootstrap/dist/css/bootstrap.min.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const inter = Montserrat({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider theme={
            {
              "token": {
                fontFamily:inter.style.fontFamily,
                "colorPrimary": "#6a37f4",
                "colorInfo": "#6a37f4"
              }
            }
          }>
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
